name: 'Helm Installer Test'
description: 'GitHub Action to install Helm'
branding:
  icon: 'download-cloud'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.helm-version }}
    - ${{ inputs.args }}
inputs:
  helm-version:
    required: true
    default: '3.12.3'
  args:
    required: true